version: 1
frontend:
  phases:
    install:
      runtime-versions:
        nodejs: 14
      commands:
        - npm install -g @aws-amplify/cli
        - npm install
    preBuild:
      commands:
        - amplify --version
        - yarn install
    build:
      commands:
        - API_URL=${API_URL}
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*